# Use rose-pine-moon color palette
palette = "rose-pine-moon"

# Simulate a right-side prompt using $fill
format = """
$directory\
$git_branch\
$git_status\
$cmd_duration\
$fill\
$time$battery${custom.devenv}\n \
$character\
"""

# Color palette
[palettes.rose-pine-moon]
overlay = '#393552'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ea9a97'
pine = '#3e8fb0'
foam = '#9ccfd8'
iris = '#c4a7e7'
lavender = "#b5c1f5"

# Directory
[directory]
style = "fg:pine"
format = "[ $path ]($style) "
truncation_length = 3
truncation_symbol = "…/"

# Git branch
[git_branch]
symbol = ""
style = "fg:foam"
format = "[$symbol $branch]($style) "

# Git status
[git_status]
style = "fg:love"
format = '[$all_status$ahead_behind]($style) '

# Fill (pushes following modules to right side in bash)
[fill]
symbol = " "
style = "fg:overlay"

# Time
[time]
disabled = true
style = "fg:rose"
format = "[$time  ]($style) "
time_format = "%H:%M"

# Battery
[battery]
disabled = true
format = "[$symbol$percentage]($style) "
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "

[[battery.display]]
threshold = 100
style = "fg:gold"

# Command duration
[cmd_duration]
min_time = 1000
format = "took [$duration](fg:gold) "

# Prompt character
[character]
success_symbol = "[➜](bold rose)"
error_symbol = "[➜](bold love)"


[custom.devenv]
disabled = false
command = "echo  $DEVENV"
when = "env | grep -q '^DEVENV='"
style = "fg:rose"
