FROM archlinux:latest

ENV EDITOR=nvim
ENV VISUAL=nvim
# ------------------------------------------------------------
# Initialize pacman keyring
# ------------------------------------------------------------
RUN pacman-key --init && \
    pacman-key --populate archlinux
# ------------------------------------------------------------
# Base system + dev tools
# ------------------------------------------------------------
RUN pacman -Syu --noconfirm \
    ca-certificates \
    bash-completion \
    gcc \
    bat \
    curl \
    git \
    sudo \
    tmux \
    neovim \
    ripgrep \
    fd \
    fzf \
    direnv \
    wl-clipboard \
    stow \
    starship \
    jq \
    unzip \
    tar \
    less \
    man-db \
    tldr \
    && pacman -Scc --noconfirm
