FROM archlinux:latest

ENV EDITOR=nvim
ENV VISUAL=nvim

# ------------------------------------------------------------
# Base system + dev tools
# ------------------------------------------------------------
RUN pacman -Syu --noconfirm \
    ca-certificates \
    gcc \
    bat \
    curl \
    git \
    sudo \
    zsh \
    tmux \
    neovim \
    ripgrep \
    fd \
    fzf \
    direnv \
    wl-clipboard \
    stow \
    starship \
    yazi \
    ffmpeg \
    p7zip \
    jq \
    poppler \
    resvg \
    imagemagick \
    unzip \
    tar \
    less \
    man-db \
    && pacman -Scc --noconfirm
